name: XPStore
version: ${project.version}
main: com.jolly.xPStore.XPStore
api-version: "26.1.2"
authors: [Jolly, trassert]
folia-supported: true
description: Allows XP storing into glassbottle
permissions:
  xpstore.use:
    description: Allows the player to use XP Bottling
    default: true